export const tradeData = [
  {
    value: 1,
    show: "Electronics Fitter / Radio Fitter",
    group: "1",
    service: 2,
  },
  {
    value: 2,
    show: "Electronics Fitter / Radar Fitter",
    group: "1",
    service: 2,
  },
  {
    value: 3,
    show: "Electronics Fitter / Missile Fitter (L)",
    group: "1",
    service: 2,
  },
  {
    value: 4,
    show: "Electrical Fitter / Instrument Fitter",
    group: "1",
    service: 2,
  },
  {
    value: 5,
    show: "Electrical Fitter / Missile Fitter (E)",
    group: "1",
    service: 2,
  },
  {
    value: 6,
    show: "Electrical Fitter / Plant Maintenance Fitter (E)",
    group: "1",
    service: 2,
  },
  {
    value: 7,
    show: "Electrical Fitter / Photo Fitter",
    group: "1",
    service: 2,
  },
  {
    value: 8,
    show: "Electrical Fitter / Electrical Fitter",
    group: "1",
    service: 2,
  },
  {
    value: 9,
    show: "Mechanical system Fitter / Missile Fitter (M)",
    group: "1",
    service: 2,
  },
  {
    value: 10,
    show: "Mechanical system Fitter / Plant Maintenance Fitter (M)",
    group: "1",
    service: 2,
  },
  {
    value: 11,
    show: "Structure Fitter / Air Frame Fitter",
    group: "1",
    service: 2,
  },
  {
    value: 12,
    show: "Propulsion Fitter / Engine Fitter",
    group: "1",
    service: 2,
  },
  {
    value: 13,
    show: "Workshop Fit (Smith) / Workshop Fitter (B)",
    group: "1",
    service: 2,
  },
  {
    value: 14,
    show: "Workshop Fit (Smith) / Workshop Fitter (C)",
    group: "1",
    service: 2,
  },
  {
    value: 15,
    show: "Workshop Fit (M) / Workshop Fit (M)",
    group: "1",
    service: 2,
  },
  {
    value: 16,
    show: "Automobile Fit / Mechanical Transport Fitter",
    group: "1",
    service: 2,
  },
  { value: 17, show: "Weapon Fit", group: "1", service: 2 },
  { value: 18, show: "Education Instructor", group: "1", service: 2 },
  {
    value: 19,
    show: "Auto Technician / Mechanical Transport Technician",
    group: "2",
    service: 2,
  },
  {
    value: 20,
    show: "Auto Technician / Mechanical Transport Driver",
    group: "2",
    service: 2,
  },
  {
    value: 21,
    show: "Communication Tech / Radio Technician",
    group: "2",
    service: 2,
  },
  {
    value: 22,
    show: "Communication Tech / Telest RT Operator",
    group: "2",
    service: 2,
  },
  {
    value: 23,
    show: "Adm Assistant / Clerk General Duties",
    group: "2",
    service: 2,
  },
  {
    value: 24,
    show: "Adm Assistant / Catering Assistant",
    group: "2",
    service: 2,
  },
  {
    value: 25,
    show: "Accts Assistant / Clerk Equipment Accounting",
    group: "2",
    service: 2,
  },
  {
    value: 26,
    show: "Accts Assistant / Clerk Pay Accounting",
    group: "2",
    service: 2,
  },
  {
    value: 27,
    show: "Ops Assistant / Air Defence Systems Operator",
    group: "2",
    service: 2,
  },
  {
    value: 28,
    show: "Ops Assistant / Air Field Safety Operator",
    group: "2",
    service: 2,
  },
  {
    value: 29,
    show: "Environmental Support Services Assistant (ESSA) / Aircraft Hand General Duties",
    group: "2",
    service: 2,
  },
  {
    value: 30,
    show: "Logistics Assistant / Equipment Assistant",
    group: "2",
    service: 2,
  },
  { value: 31, show: "Group Training Instructor", group: "2", service: 2 },
  { value: 32, show: "Indian Air Force (Police)", group: "2", service: 2 },
  { value: 33, show: "Indian Air Force (Security)", group: "2", service: 2 },
  { value: 34, show: "Medical Assistant", group: "2", service: 2 },
  { value: 35, show: "Meterorological Assistant", group: "2", service: 2 },
  { value: 36, show: "Musician", group: "3", service: 2 },
];

export const recordOffices = [
  {
    value: 1,
    show: "Army Records Office (ARO) - New Delhi",
    service: 1,
  },
  {
    value: 2,
    show: "Army Records Information Management System (ARIMS) - Pune",
    service: 1,
  },
  {
    value: 3,
    show: "Records Office, Corps of Military Police (R O CMP) - Bangalore",
    service: 1,
  },
  {
    value: 4,
    show: "Air Force Record Office (AFRO) - New Delhi",
    service: 2,
  },
  {
    value: 5,
    show: "Central Airmen Selection Board (CASB) - New Delhi",
    service: 2,
  },
  {
    value: 6,
    show: "Air Headquarters Directorate of Personnel (A1) - New Delhi",
    service: 2,
  },

  {
    value: 7,
    show: "Naval Records Office (NRO) - Mumbai",
    service: 3,
  },
  {
    value: 8,
    show: "Naval Personnel Records Office (NPRO) - New Delhi",
    service: 3,
  },
  {
    value: 9,
    show: "Records Office, Western Naval Command (ROWNC) - Mumbai",
    service: 3,
  },
];
