export const tradeData = [
  {
    value: 1,
    show: "Electronics Fitter / Radio Fitter",
    group: "1",
    service: 2,
  },
  {
    value: 2,
    show: "Electronics Fitter / Radar Fitter",
    group: "1",
    service: 2,
  },
  {
    value: 3,
    show: "Electronics Fitter / Missile Fitter (L)",
    group: "1",
    service: 2,
  },
  {
    value: 4,
    show: "Electrical Fitter / Instrument Fitter",
    group: "1",
    service: 2,
  },
  {
    value: 5,
    show: "Electrical Fitter / Missile Fitter (E)",
    group: "1",
    service: 2,
  },
  {
    value: 6,
    show: "Electrical Fitter / Plant Maintenance Fitter (E)",
    group: "1",
    service: 2,
  },
  {
    value: 7,
    show: "Electrical Fitter / Photo Fitter",
    group: "1",
    service: 2,
  },
  {
    value: 8,
    show: "Electrical Fitter / Electrical Fitter",
    group: "1",
    service: 2,
  },
  {
    value: 9,
    show: "Mechanical system Fitter / Missile Fitter (M)",
    group: "1",
    service: 2,
  },
  {
    value: 10,
    show: "Mechanical system Fitter / Plant Maintenance Fitter (M)",
    group: "1",
    service: 2,
  },
  {
    value: 11,
    show: "Structure Fitter / Air Frame Fitter",
    group: "1",
    service: 2,
  },
  {
    value: 12,
    show: "Propulsion Fitter / Engine Fitter",
    group: "1",
    service: 2,
  },
  {
    value: 13,
    show: "Workshop Fit (Smith) / Workshop Fitter (B)",
    group: "1",
    service: 2,
  },
  {
    value: 14,
    show: "Workshop Fit (Smith) / Workshop Fitter (C)",
    group: "1",
    service: 2,
  },
  {
    value: 15,
    show: "Workshop Fit (M) / Workshop Fit (M)",
    group: "1",
    service: 2,
  },
  {
    value: 16,
    show: "Automobile Fit / Mechanical Transport Fitter",
    group: "1",
    service: 2,
  },
  { value: 17, show: "Weapon Fit", group: "1", service: 2 },
  { value: 18, show: "Education Instructor", group: "1", service: 2 },
  {
    value: 19,
    show: "Auto Technician / Mechanical Transport Technician",
    group: "2",
    service: 2,
  },
  {
    value: 20,
    show: "Auto Technician / Mechanical Transport Driver",
    group: "2",
    service: 2,
  },
  {
    value: 21,
    show: "Communication Tech / Radio Technician",
    group: "2",
    service: 2,
  },
  {
    value: 22,
    show: "Communication Tech / Telest RT Operator",
    group: "2",
    service: 2,
  },
  {
    value: 23,
    show: "Adm Assistant / Clerk General Duties",
    group: "2",
    service: 2,
  },
  {
    value: 24,
    show: "Adm Assistant / Catering Assistant",
    group: "2",
    service: 2,
  },
  {
    value: 25,
    show: "Accts Assistant / Clerk Equipment Accounting",
    group: "2",
    service: 2,
  },
  {
    value: 26,
    show: "Accts Assistant / Clerk Pay Accounting",
    group: "2",
    service: 2,
  },
  {
    value: 27,
    show: "Ops Assistant / Air Defence Systems Operator",
    group: "2",
    service: 2,
  },
  {
    value: 28,
    show: "Ops Assistant / Air Field Safety Operator",
    group: "2",
    service: 2,
  },
  {
    value: 29,
    show: "Environmental Support Services Assistant (ESSA) / Aircraft Hand General Duties",
    group: "2",
    service: 2,
  },
  {
    value: 30,
    show: "Logistics Assistant / Equipment Assistant",
    group: "2",
    service: 2,
  },
  { value: 31, show: "Group Training Instructor", group: "2", service: 2 },
  { value: 32, show: "Indian Air Force (Police)", group: "2", service: 2 },
  { value: 33, show: "Indian Air Force (Security)", group: "2", service: 2 },
  { value: 34, show: "Medical Assistant", group: "2", service: 2 },
  { value: 35, show: "Meterorological Assistant", group: "2", service: 2 },
  { value: 36, show: "Musician", group: "3", service: 2 },
];

export const recordOffices = [
  {
    value: 1,
    show: "Army Records Office (ARO) - New Delhi",
    service: 1,
  },
  {
    value: 2,
    show: "Army Records Information Management System (ARIMS) - Pune",
    service: 1,
  },
  {
    value: 3,
    show: "Records Office, Corps of Military Police (R O CMP) - Bangalore",
    service: 1,
  },
  {
    value: 4,
    show: "Air Force Record Office (AFRO) - New Delhi",
    service: 2,
  },
  {
    value: 5,
    show: "Central Airmen Selection Board (CASB) - New Delhi",
    service: 2,
  },
  {
    value: 6,
    show: "Air Headquarters Directorate of Personnel (A1) - New Delhi",
    service: 2,
  },

  {
    value: 7,
    show: "Naval Records Office (NRO) - Mumbai",
    service: 3,
  },
  {
    value: 8,
    show: "Naval Personnel Records Office (NPRO) - New Delhi",
    service: 3,
  },
  {
    value: 9,
    show: "Records Office, Western Naval Command (ROWNC) - Mumbai",
    service: 3,
  },
];

export const decorations = [
  { show: "Param Vir Chakra", value: "pvc" },
  { show: "Ashoka Chakra", value: "ashoka_chakra" },
  { show: "Maha Vir Chakra", value: "mvc" },
  { show: "Kirti Chakra", value: "kirti_chakra" },
  { show: "Vir Chakra", value: "vir_chakra" },
  { show: "Shaurya Chakra", value: "shaurya_chakra" },
  { show: "Sena Medal", value: "sena_medal" },
  { show: "Nao Sena Medal", value: "nao_sena_medal" },
  { show: "Vayu Sena Medal", value: "vayu_sena_medal" },
  { show: "Mention in Despatches", value: "mention_in_despatches" },
  {
    show: "President's Police Medal for Gallantry",
    value: "presidents_police_medal_for_gallantry",
  },
  {
    show: "President's Fire Service Medal for Gallantry",
    value: "presidents_fire_service_medal_for_gallantry",
  },
  {
    show: "Sarvottam Jeevan Raksha Padak",
    value: "sarvottam_jeevan_raksha_padak",
  },
  { show: "Uttam Jeevan Raksha Padak", value: "uttam_jeevan_raksha_padak" },
  { show: "Jeevan Raksha Padak", value: "jeevan_raksha_padak" },
  { show: "Raksha Medal", value: "raksha_medal" },
  { show: "Vishisht Seva Medal (VSM)", value: "vishisht_seva_medal" },
  { show: "Yudh Seva Medal", value: "yudh_seva_medal" },
  { show: "Special Service Medal", value: "special_service_medal" },
  { show: "Operation Vijay Star", value: "operation_vijay_star" },
  { show: "Operation Parakram Medal", value: "operation_parakram_medal" },
  { show: "High-Altitude Service Medal", value: "high_altitude_service_medal" },
];

export const religionCastes = {
  religions: [
    { show: "Hinduism", value: "hinduism" },
    { show: "Islam", value: "islam" },
    { show: "Christianity", value: "christianity" },
    { show: "Sikhism", value: "sikhism" },
    { show: "Buddhism", value: "buddhism" },
    { show: "Jainism", value: "jainism" },
    { show: "Zoroastrianism (Parsi)", value: "zoroastrianism" },
  ],
  castes: {
    hinduism: [
      { show: "Brahmin", value: "brahmin" },
      { show: "Kshatriya", value: "kshatriya" },
      { show: "Vaishya", value: "vaishya" },
      { show: "Shudra", value: "shudra" },
      { show: "Dalit", value: "dalit" },
      { show: "Jat", value: "jat" },
      { show: "Rajput", value: "rajput" },
      { show: "Yadav", value: "yadav" },
      { show: "Lingayat", value: "lingayat" },
    ],
    islam: [
      { show: "Sunni", value: "sunni" },
      { show: "Shia", value: "shia" },
      { show: "Sufi", value: "sufi" },
      { show: "Ahmadiyya", value: "ahmadiyya" },
    ],
    christianity: [
      { show: "Roman Catholic", value: "roman_catholic" },
      { show: "Protestant (Various denominations)", value: "protestant" },
      { show: "Orthodox", value: "orthodox" },
      { show: "Syro-Malabar", value: "syro_malabar" },
      { show: "Syro-Malankara", value: "syro_malankara" },
    ],
    sikhism: [
      { show: "Jat Sikh", value: "jat_sikh" },
      { show: "Khatri", value: "khatri" },
      { show: "Arora", value: "arora" },
      { show: "Ramgarhia", value: "ramgarhia" },
    ],
    buddhism: [
      { show: "Theravada", value: "theravada" },
      { show: "Mahayana", value: "mahayana" },
      { show: "Vajrayana (Tibetan Buddhism)", value: "vajrayana" },
    ],
    jainism: [
      { show: "Digambara", value: "digambara" },
      { show: "Shwetambara", value: "shwetambara" },
      { show: "Sthanakvasi", value: "sthanakvasi" },
      { show: "Terapanthi", value: "terapanthi" },
    ],
    zoroastrianism: [
      { show: "Parsi", value: "parsi" },
      { show: "Irani", value: "irani" },
    ],
  },
};
